spring:
  datasource:
    url: ${CODECHELLA_DDD_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      dialect: org.hibernate.dialect.HSQLDialect
      ddl-auto: create-drop