spring:
  application.name: "adopetThreads"
  datasource:
    url: ${DATASOURCE_URL_ADOPET_STORE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: host
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  security:
    token:
      secret: ${TOKEN_PASSWORD}