spring:
  datasource:
    url: ${DATASOURCE_URL_ADOPET_STORE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    error:
      include-stacktrace: never
  mail:
    host: host
    port: 587
    username: ${EMAIL}
    password: ${SENHA_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  security:
    token:
      secret: ${TOKEN_PASSWORD:12345}