spring:
  datasource:
    url: ${DATASOURCE_URL_ADOPET}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${SENHA_EMAIL}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    error:
      include-stacktrace: never