spring:
  datasource:
    url: ${DATASOURCE_URL_ADOPET}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  mail:
    host: smtp.example.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    error:
      include-stacktrace: never