spring:
  datasource:
    url: ${ADOPET_STORE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    error:
      include-stacktrace: never
  mail:
    host: host
    port: 587
    username: ${EMAIL}
    password: ${SENHA_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  threads:
    virtual:
      enabled: true
app:
  security:
    token:
      secret: ${TOKEN_PASSWORD:12345}