# Arquivo onde vamos declara o que nossa aplicação precisa

# Instalar o node
FROM nodejs/

# Instalar a aplicação
    # rodar um yarn || npm install

# Build da aplicação
    # rodar yarn run build || npm run build

# Subir a aplicação
    # rodar yarn run start || npm run start