spring:
  datasource:
    url: ${CODECHELLA_API_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      minimum-idle: 15
      maximum-pool-size: 40
      connectionTimeout: 10000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: redis
    port: 6379
app:
  security:
    jwt:
      secret: 1234567