spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/codechella_api"
    url: ${CODECHELLA_API_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  security:
    jwt:
      secret: 1234567